import Head from 'next/head';

type HeadProps = {
  title?: string;
};

export const BaseHead = (props: HeadProps) => (
  <Head>
    <title>{props.title ?? '산넘어산'}</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
);
