import Header from '@/component/Header/Header';
import Head from 'next/head';
import React from 'react';
import ClimbUpIcon from '@/assets/icon/icon_up.svg';
import ClimbDownIcon from '@/assets/icon/icon_down.svg';
import { api } from '@/service/api';
import { GetServerSidePropsContext } from 'next';
import { ProveData, RemoteSanData } from '@/service/api/types/san';
import Image from 'next/image';

interface ProveDetailProps {
  sanData: RemoteSanData;
  proveData: ProveData;
}

export default function ProveDetail(props: ProveDetailProps) {
  const { sanData, proveData } = props;
  const userName = '남주영';
  return (
    <div>
      <Head>
        <title>산넘어산 등반 기록</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="san-detail">
        <div className="san-grid-table">
          <div className="title-wrapper">
            <div className="title">
              {userName}님의 <br />
              {sanData.name} 등반 기록
            </div>
          </div>
          <div className="level-wrapper">
            <div>level</div>
            <div>{sanData.level}</div>
          </div>
          <div className="height-wrapper">
            <div>height</div>
            <div>{sanData.height}</div>
          </div>
          <div className="length-wrapper">
            <div>length</div>
            <div>{sanData.length}</div>
          </div>
          <div className="time-wrapper">
            <div>climbing{'\n'}time</div>
            <div>
              <div>
                <ClimbUpIcon />
                <div>2:30</div>
              </div>
              <div>
                <ClimbDownIcon />
                <div>3:00</div>
              </div>
            </div>
          </div>
        </div>
        <div className="image-wrapper">
          <Image
            src={proveData.image}
            alt={sanData.name}
            layout="responsive"
            width="100%"
            height="100%"
            objectFit="cover"
          />
        </div>
        {proveData.comment.length !== 0 && <div className="comment-wrapper">{proveData.comment}</div>}
        <div className="prove-button-wrapper">
          <button className="prove-button">나도 등반 인증하기</button>
        </div>
      </section>
    </div>
  );
}

export async function getServerSideProps({ params }: GetServerSidePropsContext) {
  const sanID = +(params?.sanID ?? -1);
  const proveID = +(params?.proveID ?? -1);
  const response = await Promise.all([api.sanService.getSanDetail(sanID), api.sanService.getProveDetail(proveID)]);
  return { props: { sanData: response[0], proveData: response[1] } };
}
