import type { GetServerSidePropsContext } from 'next';
import Head from 'next/head';
import Header from '@/component/Header/Header';
import { RemoteSanData } from '@/service/api/types/san';
import { api } from '@/service/api';
import Image from 'next/image';
import ProceedIcon from '@/assets/icon/icon_proceed.svg';
import ShareIcon from '@/assets/icon/icon_share.svg';
import ClimbUpIcon from '@/assets/icon/icon_up.svg';
import ClimbDownIcon from '@/assets/icon/icon_down.svg';

function SanDetail({ sanData }: { sanData: RemoteSanData }) {
  const { name, level, height, length, defaultImage } = sanData;
  return (
    <main>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <section className="san-detail">
        <div className="san-grid-table">
          <div className="title-wrapper">
            <div className="title">북한산</div>
          </div>
          <div className="level-wrapper">
            <div>level</div>
            <div>{level}</div>
          </div>
          <div className="height-wrapper">
            <div>height</div>
            <div>{height}</div>
          </div>
          <div className="length-wrapper">
            <div>length</div>
            <div>{length}</div>
          </div>
          <div className="time-wrapper">
            <div>climbing{'\n'}time</div>
            <div>
              <div>
                <ClimbUpIcon />
                <div>2:30</div>
              </div>
              <div>
                <ClimbDownIcon />
                <div>3:00</div>
              </div>
            </div>
          </div>
        </div>
        <div className="image-wrapper">
          <Image src={defaultImage} alt={name} layout="responsive" width="100%" height="100%" objectFit="cover" />
        </div>
        <div className="button-wrapper">
          <ShareIcon />
          <div />
          <ProceedIcon />
        </div>
      </section>
    </main>
  );
}

export async function getServerSideProps({ params }: GetServerSidePropsContext) {
  const id = +(params?.id ?? -1);
  const response = await api.sanService.getSanDetail(id);
  return { props: { sanData: response } };
}

export default SanDetail;
