import type { NextPage } from 'next';
import Head from 'next/head';
import Header from '@/component/Header/Header';
import CarouselContainer from '@/component/MainCarousel/CarouselContainer';

const Home: NextPage = () => {
  return (
    <main>
      <Head>
        <title>산넘어산</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <CarouselContainer />
    </main>
  );
};

export default Home;
