name: 'CI'

on: push

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Run Lint
        run: yarn run lint
        if: ${{ always() }}
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Check types
        run: tsc -p tsconfig.json --noEmit
        if: ${{ always() }}
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Run Test
        run: yarn test:ci
        if: ${{ always() }}
  send-slack:
    runs-on: ubuntu-latest
    needs: [lint-format, type-check, unit-test]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
    
    - name: Send slack when failed
      if: ${{ failure() }}
      uses: ./.github/actions/slack-notify
      with:
        slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
    - name: Send slack if completed
      if: ${{ success() }}
      uses: ./.github/actions/slack-notify
      with:
        status: success
        slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
