name: 'CI'

on: push

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [16]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn install

  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [16]
    needs: install-dependencies
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Run lint
        run: |
          yarn run lint
        if: ${{ always() }}

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [16]
    needs: install-dependencies
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Check types
        run: |
          yarn run tsc
        if: ${{ always() }}

  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
      node: [16]
    needs: install-dependencies
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Run Test
        run: |
          yarn test:ci
        if: ${{ always() }}
