name: 'CI'

on: push

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
      - name: Install Dependencies
        run: yarn install
      - name: Run Lint
        run: yarn run lint
        if: ${{ always() }}
      - name: Check types
        run: yarn run tsc
        if: ${{ always() }}
      - name: Run Test
        run: yarn test:ci
        if: ${{ always() }}
      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
