name: 'test-every-push'

on: push

jobs:
  test:
    name: Test lint, tsc, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install

      - run: yarn run lint
        if: ${{ always() }}

      - run: yarn run tsc
        if: ${{ always() }}

      - run: yarn run build
        if: ${{ always() }}

      - name: Send slack when failed
        if: ${{ failure() }}
        uses: ./.github/actions/slack-notify
        with:
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}

      - name: Send slack if completed
        if: ${{ success() }}
        uses: ./.github/actions/slack-notify
        with:
          status: success
          slack_incoming_url: ${{ secrets.SLACK_INCOMING_URL }}
