name: 'test-every-push'

on: push

jobs:
  test:
    name: Test lint, tsc, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}

      - name: Install Dependencies
        run: yarn install
